sudo: required
services:
  - docker
before_install:
  - docker build -t docker-react -f ./client/Dockerfile.dev .
script:
  - docker run -e CI=true docker-react npm test -- --coverage
after_success:
  - docker build -t elpachanga1/multi-client ./client
  - docker build -t elpachanga1/multi-nginx ./nginx
  - docker build -t elpachanga1/multi-server ./server
  - docker build -t elpachanga1/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push elpachanga1/multi-client
  - docker push elpachanga1/multi-nginx
  - docker push elpachanga1/multi-server
  - docker push elpachanga1/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-691457164853"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY